#!/usr/bin/env bash
set -e
set -o pipefail

BUILD_DIR=$1 

ln -s ${BUILD_DIR}/vendor /app/vendor

export PATH=/app/vendor/mono/bin:$PATH

${BUILD_DIR}/vendor/mono/bin/xbuild ${BUILD_DIR}/SampleCommandlineApp/SampleCommandlineApp.sln
